### ISSUE TITLE
Cannot replicate lemonbar

### ISSUE THREAD

**Issue by snazzybunny** [brianclemens/dotfiles#7]
Hello there. I can't seem to replicate lemonbar. It seems all of the icons on the top left arent showing up and I don't think there's a mpv_functions file included. Thanks.

**Comment by confusedlinuxgirl** [comment]
At least in my copy of the git clone I didn't have the mpv function file either, nor can I get the lemonbar to work properly. Please fix!

**Comment by IegitXcuti0n** [comment]
Same way for me. No mvp_functions file as well as icons not showing up. Get this:
`/home/$user/bin/panel_bar: line 109: printf: write error: Broken pipe`
as well as this:
`mpv_functions:.:5: no such file or directory: mpv_functions`

The Broken Pipe error may have something to do with why the icons aren't showing up. These errors appear after stopping bspwm. The Broken pipe error spams the terminal until you can stop the process.

**Comment by andyph666** [comment]
You dont need the mpv functions. I got it to work by having "bspc subscribe report > "$PANEL_FIFO" &" and then commenting out bspc control --subscribe >"$PANEL_FIFO" &" so it looks like this: `bspc subscribe report > "$PANEL_FIFO" &
#bspc control --subscribe >"$PANEL_FIFO" &`

**Comment by IegitXcuti0n** [comment]
Incredible. Thank you so much!

**Comment by inject3d** [comment]
Thanks Andy! I've been away from Linux for a while and will be rolling that change into the configuration.  Not sure where my mpv_functions script went :/

**Comment by j4yz** [comment]
It's still missing, just saying. ;)

**Comment by brianclemens** [comment]
@j4yz Sorry about that.  I ended up ditching mpd / mopidy on my laptop in favor of cmus, which I find to be a better fit for my use case.  Also switched to polybar as it's quite a bit more efficient when compared to the mess of batch scripts I was using to power lemonbar.  All of those files are still available under the 1.0 tag
